// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLJhgXUv-ou1N0Z4vm8hu9sce6pz-0dKg',
    appId: '1:1059656065152:web:443eda770d25bdc6050665',
    messagingSenderId: '1059656065152',
    projectId: 'meal-monkey-34c88',
    authDomain: 'meal-monkey-34c88.firebaseapp.com',
    storageBucket: 'meal-monkey-34c88.firebasestorage.app',
    measurementId: 'G-DPBZZQEYXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1X3m0yVt3eAL5PYyMZBZPO1MRPVcwjcg',
    appId: '1:1059656065152:android:b9edd947fa024aa9050665',
    messagingSenderId: '1059656065152',
    projectId: 'meal-monkey-34c88',
    storageBucket: 'meal-monkey-34c88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGGR0_7PbaFm8Pik--sUeTAs1mxIDM6EM',
    appId: '1:1059656065152:ios:9541e168e8f5a088050665',
    messagingSenderId: '1059656065152',
    projectId: 'meal-monkey-34c88',
    storageBucket: 'meal-monkey-34c88.firebasestorage.app',
    androidClientId: '1059656065152-lmtb0gkdmjkkfm6gj545n686ssc53ltc.apps.googleusercontent.com',
    iosClientId: '1059656065152-o8d53jt1f1aidmcibbucbjbuqr2tvm8t.apps.googleusercontent.com',
    iosBundleId: 'com.klilmhdev.monkeymeal.monkeyMeal',
  );
}
